### ISSUE TITLE
Error when rendering reports on Windows

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder-reports#27]
I save welcome.md as welcome.mdw

I launch the "render report to html"

I get this error:
````
File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.2\python-3.5.3.amd64\lib\site-packages\spyder_reports\reportsplugin.py", line 106, in run_reports_render
    output_file = self.render_report(fname)
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.2\python-3.5.3.amd64\lib\site-packages\spyder_reports\reportsplugin.py", line 123, in render_report
    doc = Pweb(file)
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.2\python-3.5.3.amd64\lib\site-packages\pweave\pweb.py", line 63, in __init__
    self.read(reader = informat)
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.2\python-3.5.3.amd64\lib\site-packages\pweave\pweb.py", line 99, in read
    self.reader = Reader(file=self.source)
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.2\python-3.5.3.amd64\lib\site-packages\pweave\readers.py", line 35, in __init__
    self.rawtext = read_file_or_url(self.source)
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.2\python-3.5.3.amd64\lib\site-packages\pweave\readers.py", line 17, in read_file_or_url
    r = request.urlopen(source)
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.2\python-3.5.3.amd64\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.2\python-3.5.3.amd64\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.2\python-3.5.3.amd64\lib\urllib\request.py", line 489, in _open
    'unknown_open', req)
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.2\python-3.5.3.amd64\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\WinPython\basedir35\buildQt5\winpython-64bit-3.5.x.2\python-3.5.3.amd64\lib\urllib\request.py", line 1324, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: c>
````

![spyder_3 2_report_feature](https://user-images.githubusercontent.com/4312421/28244894-44da14a4-69f8-11e7-8b7b-1c716dd92656.PNG)

maybe uninstalling previous version / installing new version caused the issue ? 

PyQt5.9 windows 10 , python-3.5.3 32 bit, spyder-3.2.0dev

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at what's happening on Windows with Reports.

**Comment by rlaverde** [comment]
This is a bug in Pweave (in the 0.3 version), the windows path are detected as urls by urlib https://github.com/mpastell/Pweave/blob/master/pweave/readers.py#L12

I'm going to open a PR against Pweave with a fix.

**Comment by ccordoba12** [comment]
Great! Thanks a lot for it.

**Comment by stonebig** [comment]
I will apply the patch and retry

**Comment by stonebig** [comment]
it works with the patch. I have issues to uninstall the v0.30a though, not sure if v0.25 was better on this

**Comment by stonebig** [comment]
error when uninstalling:
````
C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.0\scripts>pip uninstall pweave
Exception:
Traceback (most recent call last):
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.0\python-3.6.2rc2.amd64\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.0\python-3.6.2rc2.amd64\lib\site-packages\pip\commands\uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.0\python-3.6.2rc2.amd64\lib\site-packages\pip\req\req_set.py", line 346, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.0\python-3.6.2rc2.amd64\lib\site-packages\pip\req\req_install.py", line 734, in uninstall
    FakeFile(dist.get_metadata_lines('entry_points.txt'))
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.0\python-3.6.2rc2.amd64\lib\configparser.py", line 763, in readfp
    self.read_file(fp, source=filename)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.0\python-3.6.2rc2.amd64\lib\configparser.py", line 718, in read_file
    self._read(f, source)
  File "C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.0\python-3.6.2rc2.amd64\lib\configparser.py", line 1092, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '<???>' [line  4]: option 'ptangle' in section 'console_scripts' already exists

C:\WinPython\basedir36\buildQt5\winpython-64bit-3.6.x.0\scripts>
````

**Comment by stonebig** [comment]
i will remove the "P" ones from setup.py

**Comment by stonebig** [comment]
I have this strange message, launching a winpython with spyder-repots and spyder-notebook for the first time:
````
  plugin.register_plugin()
    self.report_widget.set_html_from_file(html_path)
    with codecs.open(filename, encoding="utf-8") as file:
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\famille\\AppData\\Local\\Temp\\welcome.html'
````

**Comment by stonebig** [comment]
trying to look for my welcome.mdw, I see that default file search doesn't include ".mdw".

**Comment by ccordoba12** [comment]
@dalthviz, please test this plugin on Windows and fix all errors you can find. Thanks!

**Comment by dalthviz** [comment]
Testing in Windows with conda and the 2.5 version of Pweave
The installation of Pweave can't be done with `conda install -c mpastell pweave` an error raises:

**Comment by dalthviz** [comment]
@ccordoba12 testing in Windows with `conda` and the `2.5` version of `pweave`

The installation can't be done with `conda install -c mpastell pweave` an error raises:

![imagen](https://user-images.githubusercontent.com/16781833/28252967-2d278ea2-6a63-11e7-8df9-334f7c4a51c2.png)

Althought, modifing the file at `C:\...\Anaconda3\pkgs\pweave-0.25-py35_0\info\files` the installation works, but you have to manually install `pandoc` to make it work with `.md`. Also, as @stonebig say, the `.mdw` extension is not set in the filter that Spyder manages for text files, and to render that type of files you need to install `markdown` (with `conda` or `pip`).

More than that, the plugin works for me :+1:

**Comment by ccordoba12** [comment]
> I have this strange message, launching a winpython with spyder-reports and spyder-notebook for the first time

I think I know why this is happening. The rendering process has not finished when Spyder tries to read the output of Pweave, and so the error you posted.

@rlaverde, we need to use a worker to render reports. Please take a look at what @goanpeca did in https://github.com/spyder-ide/spyder/pull/3491

**Comment by ccordoba12** [comment]
@dalthviz, what happens if you run instead

    conda install -c conda-forge pweave

? Does the installation work this time?

**Comment by dalthviz** [comment]
@ccordoba12 the installation with conda-forge works, but I had to manually install `pandoc`, maybe `pandoc` should be also a dependency? Also, about the `.mdw` extension, should I create an issue in Spyder to add that extension to the filter?

**Comment by ccordoba12** [comment]
@dalthviz, please open a new PR in the conda-forge Pweave feedstock:

https://github.com/conda-forge/pweave-feedstock

and add pandoc as a dependency there.

Also, please open a PR in the Pweave repo to fix the installation instructions in its Readme, so that instead of

    conda install -c mpastell pweave

it appears there

    conda install -c conda-forge pweave

**Comment by dalthviz** [comment]
@ccordoba12 I tried again the installation with `conda-forge` in a new env and it worked without the need to install `pandoc` so I think it is ok without the dependency.

**Comment by rlaverde** [comment]
I think `pandoc` is like an optional dependencies, but It's needed hen you want to render `md` files, maybe we could add is as` spyder-reports` dependency instead

**Comment by ccordoba12** [comment]
Sure, I think that's better.

**Comment by gabrielburcea** [comment]
I have followed pretty much what is on suggested with regards to spyder-reports. And cannot actually solve this issue. I use MAC

**Comment by dalthviz** [comment]
Hi @gabrielburcea, as far as I remember, part of the problems are related to compatibility with `Pweave>=0.30` and the need of `pandoc` (although I'm unsure of what specific version) maybe you could try to check if you are using `Pweave=0.25`. Also, this plugin only works with Spyder 3. Maybe, since you use Mac, opening a new issue with the details could be worth it
